### ISSUE TITLE
On Mac OS X 10.8.5, 'ack' is confused by preceding $

### ISSUE THREAD

**Issue by tonyjiang** [beyondgrep/ack1#267]
I have such a line in file ./foo/bar/baz.config:

  $config_root=/etc/blah

When I do 'ack config_root', this file is not returned. But the good ol' unix commands work:

  find . -name "_._" -type f|xargs grep config_root

Trying to find '$config_root' with ack is also futile - likely a related issue.

**Comment by petdance** [comment]
What version of ack are you using?  If you are on 1.x, please note that ack 1.x is no longer supported.

ack is now at 2.0 and is at https://github.com/petdance/ack2.  If your problem applies to ack 2.0, please report it there. https://github.com/petdance/ack

**Comment by petdance** [comment]
I am guessing that you are using ack 1.x where ack only searched source code by default. ack 1.x would ignore *.config files unless you specifically made a type for it.  ack 2.0's default behavior is more greplike.

To be clear: I'm saying that the problem is not that ack can't find `$config_root`, but that it doesn't even look in the .config file.  Use `ack -f` to see what files ack is searching.

**Comment by tonyjiang** [comment]
Yeah ack2 worked.

I am sorry - I typed .config randomly. In reality, it was a puppet file (extension .pp). So it was probably the case that ack1 looked at it but still didn't see what I was looking for.

**Comment by petdance** [comment]
Please also have a read of the ack manual, especially the FAQ.  `ack --man` has the entire manual.
