### ISSUE TITLE
-i and -g should work together

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#87]

**Comment by blixtor** [comment]
Judging from the comments in t/ack-g.t this was working in the past (but was changed).

Are you suggesting that -i should only work in conjunction with the -g option? So if I say ack -i -f -G foo then it would NOT find a file foobar.pl?
Otherwise (if -i should apply to -G - and thus we keep the equivalence -g <=> -f -G) it is not clear, whether a specified -i should apply to -G or to the (potential) normal regex given on the command line as well: ack -i -G foo regex.

Trying to do anything clever like applying the -i just to the "closest" or "next" regex on the command line gets tricky quite quickly as the different arguments on the command line are parsed at different times - and I think it's not worth the hassle. After all, specifying the regex as (?i)regex is rather easy ...

**Comment by petdance** [comment]
They now work together in ack 2.
