### ISSUE TITLE
Add a new --nofilter option

### ISSUE THREAD

**Issue by petdance** [beyondgrep/ack1#90]
it would be nice to be able to explicitly disable filter mode for e.g. running from emacs

 Reported by techtramp, Jun 09, 2009

ack switches into filter mode if STDIN is a pipe

http://github.com/mccraigmccraig/ack/commit/de14c7f2252f67210484072cf6aee0ade2ca9c69

is a patch which adds a --nofilter option, which explicitly disables filter
mode

**Comment by csmith0651** [comment]
Perhaps a --nofilter is not necessary, instead specify "." as single filename:

% ack -i foobar .

This requires moving check that STDIN is a named pipe to after the processing of the command line arguments.

**Comment by dmmalam** [comment]
Any progress on this? I've having the same issue whilst trying to run ack from nodejs's chilld process

**Comment by petdance** [comment]
I don't think anyone is working on it, @dmmalam.  If you'd like to add a --nofilter option, I'd be open to it.

**Comment by dmmalam** [comment]
Currently Ive gotten around it by using grep, which is kinda ironic I guess
as I prefer ack.

The issue comes across when running ack from our build script, or any child
process, so I'm surprised the issue is still open. I guess most people will
be using ack interactively?

If I have time, i'll have a look at it.

Dharmesh Malam

On 23 January 2012 14:57, Andy Lester <
reply@reply.github.com

**Comment by lloeki** [comment]
Workaround: https://github.com/petdance/ack/issues/106#issuecomment-5065852

**Comment by hoelzro** [comment]
Migrated to ack2 queue.
